version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  web:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  pgdata:
